#启动端口
server:
    port: 8099

#设置随机端口
#server:
#    port: ${random.int[1024,9999]}

key2: 2222222222

#导入子配置文件
spring:
    profiles:
        include: model1,model2
        active: dev  #多环境切换配置
    main:
        banner-mode: "off"  #关闭启动时的横幅
    swagger2:
        enabled: true

#定义acme配置
acme:
    remote-address: 192.168.1.1
    security:
        username: admin
        roles:
         - USER
         - ADMIN

#配置外部logback.xml
logging:
    config: classpath:./config/logback.xml

#服务器部署用以下配置
#file在ide中是项目根目录，在执行jar文件时就是其本身目录
#logging:
#    config: file:./config/logback.xml
