application:
    name: dev environment

#定义数据源
#参考 https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE
spring:
    datasource:
            druid:
                driver-class-name: com.mysql.cj.jdbc.Driver
                type: com.alibaba.druid.pool.DruidDataSource
                url: jdbc:mysql://localhost:3306/webapp2?serverTimezone=UTC
                username: user2
                #654321
                password: ENC(TSNRe9Ou+hxupLlQ3me15Q==)
                #配置监控统计拦截的filters
                filters: stat,wall,slf4j
                max-active: 20
                initial-size: 1
                max-wait: 60000
                min-idle: 1
                time-between-eviction-runs-millis: 60000
                min-evictable-idle-time-millis: 300000
                test-while-idle: true
                test-on-borrow: false
                test-on-return: false
                pool-prepared-statements: true
                max-open-prepared-statements: 20
                async-init: true
                filter: 
                    slf4j: 
                        enabled: true
                        statement-create-after-log-enabled: false
                        statement-close-after-log-enabled: false
                        result-set-open-after-log-enabled: false
                        result-set-close-after-log-enabled: false
                    stat: 
                        enabled: true
                #合并多个DruidDataSource的监控数据（多数据源时用）
                #use-global-data-source-stat: true
                #配置监控用户和密码以及访问ip
                stat-view-servlet:
                    #默认关闭了监控页面
                    enabled: true 
                    login-username: admin
                    login-password: admin
                    allow: 127.0.0.1

#邮件发送
    mail:
      username: xxx@xxx.com
      #123456
      password: ENC(EBfyncD8izHWW8+8dFKPmw==)
      host: smtp.exmail.qq.com
      port: 465
      properties:
        mail:
          transport:
            protocol: smtp
          smtp:
            socketFactory:
              class: javax.net.ssl.SSLSocketFactory
            port: ${spring.mail.port}
            auth: true
            starttls:
              enable: true
              required: true

    rabbitmq:
        host: 72.19.12.191
        port: 5672
        username: admin
        password: admin
        virtual-host: my_vhost

#redis单机配置
#    redis:
#        database: 0
#        host: 173.254.202.227
#        port: 10079
#        password: 123_12345678^_00
#        lettuce:
#            pool:
#                max-active: 16 #连接池最大连接数（使用负值表示没有限制）
#                max-idle: 8 #连接池中的最大空闲连接
#                max-wait: 100ms #连接池最大阻塞等待时间（使用负值表示没有限制）
#                min-idle: 4 #连接池中的最小空闲连接

#redis集群配置
    redis:
        database: 0
        password: 
        cluster:
            #加入所有redis节点
            nodes: 72.19.12.191:6381,72.19.12.191:6382,72.19.12.191:6383,72.19.12.191:6384,72.19.12.191:6385,72.19.12.191:6386
        lettuce:
            pool:
                max-active: 16
                max-idle: 32
                max-wait: -1
                min-idle: 8

#mybatis的相关配置
mybatis:
    #mapper配置文件
    mapper-locations: classpath:com/create/xml/*.xml
    #resultType默认包名
    type-aliases-package: com.create.entity
    #开启驼峰命名
    configuration:
        map-underscore-to-camel-case: true

#tkMybatis配置
mapper:
    #配置继承后的通用DAO接口类
    mappers: com.example.base.BaseDao
    identity: mysql
    
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    page-size-zero: true

#限流器QPS设置
rateLimiter:
    all: 1
    resource: 100
    interface: 1

#自定义starter包
sms:
    properties:
        timeout: 1000
        retry: 6

#test对账结果通知邮箱地址
test:
  mail:
    #发件人邮箱
    from: aaa@aaa.com
    #收件人邮箱（支持同时发多个，用分号分隔）
    to: bbb@bbb.com

#yml不允许有value的key下面一层及有value，要间隔一个空的层级
#设置交换器
mq:
  config:
    exchange: log-direct
    exchange2: log-topic
    exchange3: order.fanout
    queue:
      info: log.info
      error: log.error
      info2: log.info2
      error2: log.error2
      logs: log.msg   #全消息
      sms: order.sms
      push: order.push
      routing:
        key:
          info: log.info.routing.key
          error: log.error.routing.key
          userinfo: user.log.info
          userdebug: user.log.debug
          userwarn: user.log.warn
          usererror: user.log.error
          productinfo: product.log.info
          productdebug: product.log.debug
          productwarn: product.log.warn
          producterror: product.log.error
          orderinfo: order.log.info
          orderdebug: order.log.debug
          orderwarn: order.log.warn
          ordererror: order.log.error
          


