#启动端口
server:
    port: 8099
    ssl:
        enabled: true
        #证书的路径
        key-store: classpath:saas.p12
        #证书密码
        key-store-password: 123456
        #秘钥库类型
        key-store-type: PKCS12
        #SSL协议
        protocol: TLS
        #使用TLS 1.2
        enabled-protocols: TLSv1.2
        #证书别名
        key-alias: saas

#设置随机端口
#server:
#    port: ${random.int[1024,9999]}

key2: 2222222222

#导入子配置文件
spring:
    profiles:
        include: model1,model2
        active: dev  #多环境切换配置
    main:
        banner-mode: "off"  #关闭启动时的横幅
    swagger2:
        enabled: true

#定义acme配置
acme:
    remote-address: 192.168.1.1
    security:
        username: admin
        roles:
         - USER
         - ADMIN

#配置外部logback.xml
logging:
    config: classpath:./config/logback.xml

#加密所需的salt(盐)
jasypt:
    encryptor:
        password: AD42F6697B035B7580E4FEF93BE20BAD
        #加密算法设置3.0.0以后
        algorithm: PBEWithMD5AndDES
        iv-generator-classname: org.jasypt.iv.NoIvGenerator
